name: AWS Service CI/CD PROD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test AWS CDK Typescript Stack
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."

      - name: Initiated By User
        run: echo $GITHUB_ACTOR

      - name: Check Out Code
        uses: actions/checkout@v3.1.0

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build Go Binaries
        run: |
          for d in cmd/*/; do
            if [ -d "$d" ]; then
                echo "Building in directory: $d"
                cd "$d" && GOOS=linux go build -o bootstrap . || echo "Failed to build in $d"
                cd - > /dev/null
            else
                echo "Directory $d does not exist"
            fi
          done

      - name: Install Node
        uses: actions/setup-node@v3.5.0

      - name: Install Dependencies
        run: npm install

      - name: Synth
        run: npm run synth:prod

      - name: Deploy AWS CDK Stack
        run: npm run deploy:prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
